runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: index.php

# [START env]
env_variables:
  # Replace project, instance, database, user and password with the values obtained
  # when configuring your Cloud SQL instance.
  MYSQL_DSN: "mysql:unix_socket=/cloudsql/aplicook-end-staging:us-east1:ap-api;dbname=ap_api"
  MYSQL_USER: root
  MYSQL_PASSWORD: ""
# [END env]

beta_settings:
    cloud_sql_instances: "aplicook-end-staging:us-east1:ap-api"
